version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: msbuild -t:Restore,Build,Pack -p:Configuration=Release,IncludeSymbols=true,PackageVersion=$env:appveyor_build_version
artifacts:
- path: '**/*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: +7xnWj2H6CI1zQJHcbFMDRCJcSn1HYWp2HgKSRGRn5QxmrVhkdgUcddOSsLewFkm