version: 1.0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
- ps: >-
    iwr https://dist.nuget.org/win-x86-commandline/v3.5.0-beta2/NuGet.exe -OutFile nuget.exe

    .\nuget.exe restore
build:
  verbosity: minimal
after_build:
- ps: ls -r *.nuspec | % { .\nuget.exe pack -sym $_ -Version $env:appveyor_build_version }
artifacts:
- path: '*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: +7xnWj2H6CI1zQJHcbFMDRCJcSn1HYWp2HgKSRGRn5QxmrVhkdgUcddOSsLewFkm